#!/usr/bin/python

operations = [
        "rrc",
        "swpb",
        "rra",
        "sxt",
        "push",
        "call",
        "reti",
        "jne",
        "jeq",
        "jnc",
        "jc",
        "jn",
        "jge",
        "jl",
        "jmp",
        "mov",
        "add",
        "addc",
        "subc",
        "sub",
        "cmp",
        "dadd",
        "bit",
        "bic",
        "bis",
        "xor",
        "and",
        "nop",
        "br",
        "ret",
        "pop",
]

registers = [
        "pc",
        "sp",
        "sr",
        "cg",
        "r4",
        "r5",
        "r6",
        "r7",
        "r8",
        "r9",
        "r10",
        "r11",
        "r12",
        "r13",
        "r14",
        "r15",
]


def gen_enum(header_file, prefix, items):
    print >>header_file, "enum {"
    print >>header_file, "\t%s_UNKNOWN = 0," % prefix
    for item in items:
        print >>header_file, "\t%s_%s," % (prefix, item.upper())
    print >>header_file, "};"
    print >>header_file, ""

def gen_lookup(header_file, source_file, fnname, argname,  prefix, items):
    print >>header_file, "char *%s(int %s);" % (fnname, argname)
    print >>source_file, "char *%s(int %s){" % (fnname, argname)
    print >>source_file, "\tswitch(%s){" % (argname, )
    for item in items:
        print >>source_file, '\t\tcase %s_%s:\treturn "%s";' % (prefix.upper(), item.upper(), item)
    print >>source_file, '\t\tdefault:\treturn 0;'
    print >>source_file, "\t}"
    print >>source_file, "}"
    print >>source_file, ""

with open("generated.h", "w") as header_file:
    with open("generated.c", "w") as source_file:
        print >>header_file, "// DO NOT EDIT THIS FILE"
        print >>header_file, "// EDIT generate.py INSTEAD"
        print >>header_file, ""
        print >>header_file, "#ifndef GENERATED_H"
        print >>header_file, "#define GENERATED_H"
        print >>header_file, ""
        print >>source_file, "// DO NOT EDIT THIS FILE"
        print >>source_file, "// EDIT generate.py INSTEAD"
        print >>source_file, ""
        print >>source_file, '#include "generated.h"'
        print >>source_file, ""

        gen_enum(header_file, "OPER", operations)
        gen_enum(header_file, "REG", registers)

        gen_lookup(header_file, source_file, "lookup_mnemonic_for_operation", "operation", "OPER", operations)
        gen_lookup(header_file, source_file, "lookup_reg_string", "reg", "REG", registers)

        print >>header_file, "#endif"


